insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Espresso House', '1 Blaine Circle', '7:30am-9:30pm', 94);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Sushi Samurai', '24 Summer Ridge Trail', '8:00am-10:00pm', 42);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Gelato Stand', '3072 Portage Trail', '7:30am-9:30pm', 36);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Smokehouse BBQ', '593 Gulseth Way', '7:30am-9:30pm', 52);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Pie Place', '81 Harper Crossing', '10:30am-10:30pm', 36);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Sizzling Sushi', '4040 Evergreen Drive', '8:00am-10:00pm', 59);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Gelato Stand', '50372 Waubesa Plaza', '11:00am-11:00pm', 85);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The BBQ Shack', '253 Maywood Drive', '8:00am-10:00pm', 56);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Taco Fiesta', '54801 Kipling Park', '10:30am-10:30pm', 59);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Rustic Tavern', '201 Ridge Oak Trail', '7:30am-9:30pm', 53);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Crepe Cart', '604 Reindahl Terrace', '10:30am-10:30pm', 40);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Bella Italia', '3 Lukken Trail', '7:30am-9:30pm', 30);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Candy Apple Cart', '7412 Spaight Way', '10:30am-10:30pm', 37);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Pretzel Shop', '7 Sullivan Court', '11:00am-11:00pm', 54);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Smoothie Shop', '6029 Forest Crossing', '7:30am-9:30pm', 100);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Bagel Bakery', '71223 Gerald Drive', '8:00am-10:00pm', 7);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Rustic Tavern', '29 Clarendon Plaza', '7:30am-9:30pm', 81);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Burger Joint', '73 Brickson Park Point', '7:30am-9:30pm', 48);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Noodle House', '61 Hanover Plaza', '8:00am-10:00pm', 58);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Cafe Luna', '56480 Katie Court', '7:30am-9:30pm', 32);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Bistro Breeze', '95 Bartelt Parkway', '11:00am-11:00pm', 40);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Fish Fry', '954 Porter Way', '10:30am-10:30pm', 82);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Vegan Kitchen', '85 Dawn Avenue', '10:30am-10:30pm', 82);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Pretzel Shop', '42 Ridgeway Drive', '11:00am-11:00pm', 53);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Waffle House', '56 Prairie Rose Plaza', '10:30am-10:30pm', 31);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Tapas Lounge', '89770 High Crossing Lane', '10:30am-10:30pm', 55);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Peking Garden', '907 Bunker Hill Park', '8:00am-10:00pm', 8);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Mama Mia''s', '5 Packers Lane', '7:30am-9:30pm', 64);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Bistro Breeze', '8601 Farragut Drive', '8:00am-10:00pm', 84);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Noodle House', '0334 Melby Way', '11:00am-11:00pm', 46);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Tea Room', '0 Continental Point', '10:30am-10:30pm', 84);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Fish Fry', '9789 Browning Crossing', '11:00am-11:00pm', 54);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Fish Fry', '7 Banding Alley', '8:00am-10:00pm', 38);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Tea Room', '5525 Bunker Hill Park', '10:30am-10:30pm', 70);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Golden Dragon', '02 Green Ridge Alley', '10:30am-10:30pm', 87);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cookie Jar', '509 Mallory Plaza', '10:30am-10:30pm', 86);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Burger Joint', '7436 Di Loreto Hill', '8:00am-10:00pm', 84);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The BBQ Shack', '328 Gateway Drive', '11:00am-11:00pm', 93);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Breakfast Club', '34 Northwestern Street', '10:30am-10:30pm', 8);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Popcorn Stand', '78866 Magdeline Center', '11:00am-11:00pm', 55);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Sushi Samurai', '66 Blue Bill Park Alley', '10:30am-10:30pm', 20);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Hot Dog Stand', '7 Schiller Center', '10:30am-10:30pm', 54);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Bella Italia', '8649 Golf Drive', '11:00am-11:00pm', 48);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Hot Dog Stand', '59016 Northfield Circle', '8:00am-10:00pm', 13);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Burger Joint', '7 Merrick Drive', '8:00am-10:00pm', 12);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Lemonade Stand', '4638 Talisman Avenue', '10:30am-10:30pm', 16);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Tapas Lounge', '10 Artisan Circle', '11:00am-11:00pm', 4);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Tapas Lounge', '625 Tennessee Parkway', '11:00am-11:00pm', 27);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cookie Jar', '91 Luster Park', '7:30am-9:30pm', 3);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Sandwich Spot', '257 Cottonwood Parkway', '10:30am-10:30pm', 20);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Ice Cream Parlor', '03150 Schlimgen Trail', '11:00am-11:00pm', 22);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Thai Orchid', '2262 Quincy Alley', '11:00am-11:00pm', 68);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Juice Bar', '30 Mesta Court', '10:30am-10:30pm', 33);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Candy Shop', '0617 Birchwood Point', '11:00am-11:00pm', 83);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Rustic Tavern', '87989 Sundown Drive', '11:00am-11:00pm', 93);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Bistro Breeze', '87 Shoshone Place', '11:00am-11:00pm', 69);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Burger Joint', '28755 American Ash Lane', '8:00am-10:00pm', 35);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Mama Mia''s', '2395 Mallard Junction', '7:30am-9:30pm', 9);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cookie Jar', '901 Crownhardt Crossing', '10:30am-10:30pm', 65);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Pizza Pizzazz', '72350 Killdeer Street', '7:30am-9:30pm', 64);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Bagel Bakery', '18 John Wall Terrace', '8:00am-10:00pm', 12);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Cafe Luna', '36900 Golf Course Hill', '11:00am-11:00pm', 49);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Sushi Samurai', '97108 Sunnyside Trail', '7:30am-9:30pm', 85);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Pie Place', '91880 Forest Run Park', '8:00am-10:00pm', 66);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Mama Mia''s', '1194 Heffernan Lane', '8:00am-10:00pm', 88);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Sizzling Sushi', '80138 Monica Plaza', '8:00am-10:00pm', 15);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Smokehouse BBQ', '664 Scofield Way', '7:30am-9:30pm', 10);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Noodle House', '5 Delladonna Road', '11:00am-11:00pm', 70);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Crepe Cart', '35989 Elmside Avenue', '10:30am-10:30pm', 91);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The BBQ Shack', '8581 Dovetail Trail', '11:00am-11:00pm', 27);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Breakfast Club', '7 Texas Lane', '11:00am-11:00pm', 10);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Sandwich Spot', '59 Lakewood Gardens Drive', '10:30am-10:30pm', 74);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Smokehouse BBQ', '1 Carpenter Park', '8:00am-10:00pm', 30);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Burger Joint', '21 Old Gate Drive', '8:00am-10:00pm', 75);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Taco Fiesta', '20494 Trailsway Center', '10:30am-10:30pm', 29);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Hot Dog Stand', '9 Mcbride Circle', '7:30am-9:30pm', 50);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Golden Dragon', '485 Village Green Crossing', '11:00am-11:00pm', 84);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cupcake Corner', '0 Kenwood Junction', '8:00am-10:00pm', 69);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Fish Fry', '8 Lotheville Lane', '8:00am-10:00pm', 2);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Pasta Palace', '14 Miller Trail', '7:30am-9:30pm', 51);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Pie Place', '6849 Sachs Plaza', '8:00am-10:00pm', 40);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Espresso House', '6810 Duke Circle', '8:00am-10:00pm', 93);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Peking Garden', '0324 Clemons Plaza', '10:30am-10:30pm', 100);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cookie Jar', '6504 Leroy Trail', '8:00am-10:00pm', 82);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Juice Bar', '96 Longview Alley', '8:00am-10:00pm', 72);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Frozen Yogurt Shop', '036 Bunker Hill Drive', '8:00am-10:00pm', 75);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Cookie Jar', '50 Beilfuss Trail', '7:30am-9:30pm', 18);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Taco Fiesta', '260 Erie Alley', '10:30am-10:30pm', 3);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('La Cantina', '51 John Wall Point', '7:30am-9:30pm', 51);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Taco Fiesta', '789 Cottonwood Lane', '7:30am-9:30pm', 97);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Candy Shop', '669 Forster Trail', '7:30am-9:30pm', 6);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The BBQ Shack', '25183 Cambridge Way', '11:00am-11:00pm', 8);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Cafe Luna', '27613 Nova Plaza', '10:30am-10:30pm', 26);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('La Cantina', '3 Luster Way', '7:30am-9:30pm', 31);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Flaming Grill', '786 Roth Pass', '10:30am-10:30pm', 38);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Espresso House', '0005 Sunbrook Lane', '8:00am-10:00pm', 35);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('Cafe Luna', '1 Old Shore Junction', '7:30am-9:30pm', 64);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Crepe Cart', '6 Twin Pines Crossing', '10:30am-10:30pm', 41);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Noodle House', '90 Park Meadow Road', '10:30am-10:30pm', 37);
insert into ESTABLISHMENT (establishment_name, establishment_location, operating_hours, established_by) values ('The Hungry Bear', '7 North Way', '8:00am-10:00pm', 88);
